version: '3.3'
services:
    nginxwebdav:
        container_name: nginxwebdav
        build:
            context: .
        volumes:
            - ./data:/data
            - ./htpasswd:/etc/nginx/htpasswd
        environment:
            - PUID=501
            - PGID=20
            - TZ=Europe/Berlin
            - WEBDAV_USERNAME=user
            - WEBDAV_PASSWORD=password
            - SERVER_NAMES=localhost
            - TIMEOUTS_MS=1200 # tese are seconds
            - CLIENT_MAX_BODY_SIZE="120M" # must end with M(egabytes) or G(igabytes)
        ports:
          - 32080:80
        
